import type { Metadata } from "next";

import {
  AppRouterCacheProvider,
} from '@mui/material-nextjs/v13-appRouter';
import {ThemeProvider} from '@mui/material/styles';

import theme from './theme/theme';
import { CssBaseline } from '@mui/material';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='pt-br'>
      <body>
        <AppRouterCacheProvider options={{key: 'css'}}>
          <CssBaseline />

          <ThemeProvider theme={theme}>{children}</ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
